export default `

  type Subscription {
    userAdded: User!
  }

  type Board {
    id: Int!
    name: String!
    suggestions: [Suggestion!]!
    owner: Int!
  }

  type User {
    id: Int!
    username: String!
    email: String!
    isAdmin: Boolean!
    createdAt: String!
    updatedAt: String!
    boards: [Board!]!
    suggestions: [Suggestion!]!
  }

  type AuthPayload {
    token: String!
    refreshToken: String!
  }

  type Author {
    id: Int!
    firstname: String!
    lastname: String!
    primary: Boolean
    books: [Book!]!
  }
  type Book {
    id: Int!
    title: String!
    authors: [Author!]!
  }

  type Query {
    getBook(id: Int!): Book
    allBooks(key: Int!, limit: Int!): [Book!]!
    allAuthors: [Author!]!
    allUsers: [User!]!
    me: User
    getUser(username: String!): User!
    allBoards: [Board!]!
     
    userBoards(owner: Int!): [Board!]!
    
  }

  type Mutation {
    createAuthor(firstname: String!, lastname: String!): Author!
    createBook(title: String!): Book!
    addBookAuthor(bookId: Int!, authorId: Int!, primary: Boolean!): Boolean!
    createUser(username: String!): User!
    updateUser(username: String!, newUsername: String!): [Int!]!
    deleteUser(username: String!): Int!    
    createBoard(owner: Int!, name: String!): Board!    
    register(username: String!, email: String!, password: String!, isAdmin: Boolean): User!
    login(email: String!, password: String!): AuthPayload!
    refreshTokens(token: String!, refreshToken: String!): AuthPayload!
  }

  schema {
    query: Query
    mutation: Mutation
    subscription: Subscription
  }
`;
